// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blob.proto

package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignedBlob struct {
	Payload              []byte     `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature            *Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SignedBlob) Reset()         { *m = SignedBlob{} }
func (m *SignedBlob) String() string { return proto.CompactTextString(m) }
func (*SignedBlob) ProtoMessage()    {}
func (*SignedBlob) Descriptor() ([]byte, []int) {
	return fileDescriptor_blob_4ba19cbf5de0df56, []int{0}
}
func (m *SignedBlob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedBlob.Unmarshal(m, b)
}
func (m *SignedBlob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedBlob.Marshal(b, m, deterministic)
}
func (dst *SignedBlob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedBlob.Merge(dst, src)
}
func (m *SignedBlob) XXX_Size() int {
	return xxx_messageInfo_SignedBlob.Size(m)
}
func (m *SignedBlob) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedBlob.DiscardUnknown(m)
}

var xxx_messageInfo_SignedBlob proto.InternalMessageInfo

func (m *SignedBlob) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SignedBlob) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Signature struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_blob_4ba19cbf5de0df56, []int{1}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PermanodeMeta struct {
	Rnd                  string   `protobuf:"bytes,1,opt,name=rnd,proto3" json:"rnd,omitempty"`
	CreateTimestamp      int64    `protobuf:"varint,2,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermanodeMeta) Reset()         { *m = PermanodeMeta{} }
func (m *PermanodeMeta) String() string { return proto.CompactTextString(m) }
func (*PermanodeMeta) ProtoMessage()    {}
func (*PermanodeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_blob_4ba19cbf5de0df56, []int{2}
}
func (m *PermanodeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermanodeMeta.Unmarshal(m, b)
}
func (m *PermanodeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermanodeMeta.Marshal(b, m, deterministic)
}
func (dst *PermanodeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermanodeMeta.Merge(dst, src)
}
func (m *PermanodeMeta) XXX_Size() int {
	return xxx_messageInfo_PermanodeMeta.Size(m)
}
func (m *PermanodeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PermanodeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PermanodeMeta proto.InternalMessageInfo

func (m *PermanodeMeta) GetRnd() string {
	if m != nil {
		return m.Rnd
	}
	return ""
}

func (m *PermanodeMeta) GetCreateTimestamp() int64 {
	if m != nil {
		return m.CreateTimestamp
	}
	return 0
}

type FileNode struct {
	Meta                 *PermanodeMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Filename             string           `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size                 int64            `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	BlobSize             int64            `protobuf:"varint,4,opt,name=blob_size,json=blobSize,proto3" json:"blob_size,omitempty"`
	BlobRefs             map[int64]string `protobuf:"bytes,5,rep,name=blobRefs,proto3" json:"blobRefs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FileNode) Reset()         { *m = FileNode{} }
func (m *FileNode) String() string { return proto.CompactTextString(m) }
func (*FileNode) ProtoMessage()    {}
func (*FileNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_blob_4ba19cbf5de0df56, []int{3}
}
func (m *FileNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileNode.Unmarshal(m, b)
}
func (m *FileNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileNode.Marshal(b, m, deterministic)
}
func (dst *FileNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileNode.Merge(dst, src)
}
func (m *FileNode) XXX_Size() int {
	return xxx_messageInfo_FileNode.Size(m)
}
func (m *FileNode) XXX_DiscardUnknown() {
	xxx_messageInfo_FileNode.DiscardUnknown(m)
}

var xxx_messageInfo_FileNode proto.InternalMessageInfo

func (m *FileNode) GetMeta() *PermanodeMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *FileNode) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileNode) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileNode) GetBlobSize() int64 {
	if m != nil {
		return m.BlobSize
	}
	return 0
}

func (m *FileNode) GetBlobRefs() map[int64]string {
	if m != nil {
		return m.BlobRefs
	}
	return nil
}

func init() {
	proto.RegisterType((*SignedBlob)(nil), "schema.SignedBlob")
	proto.RegisterType((*Signature)(nil), "schema.Signature")
	proto.RegisterType((*PermanodeMeta)(nil), "schema.PermanodeMeta")
	proto.RegisterType((*FileNode)(nil), "schema.FileNode")
	proto.RegisterMapType((map[int64]string)(nil), "schema.FileNode.BlobRefsEntry")
}

func init() { proto.RegisterFile("blob.proto", fileDescriptor_blob_4ba19cbf5de0df56) }

var fileDescriptor_blob_4ba19cbf5de0df56 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x4d, 0x29, 0x20, 0x1d, 0x20, 0xe2, 0x46, 0x93, 0x06, 0x8d, 0x21, 0x9c, 0xe0, 0x52, 0x13,
	0xbc, 0x18, 0x8c, 0x17, 0x12, 0x3d, 0xa9, 0x31, 0x8b, 0x89, 0x47, 0xb2, 0xa5, 0x03, 0x36, 0xb6,
	0xdd, 0x66, 0xbb, 0x98, 0xd4, 0xbf, 0xee, 0xc5, 0xec, 0x94, 0xad, 0xe2, 0xed, 0xcd, 0x7b, 0x6f,
	0xdf, 0x7c, 0x2c, 0x40, 0x98, 0xc8, 0x30, 0xc8, 0x95, 0xd4, 0x92, 0xb5, 0x8b, 0xf5, 0x3b, 0xa6,
	0x62, 0xfc, 0x06, 0xb0, 0x8c, 0xb7, 0x19, 0x46, 0x8b, 0x44, 0x86, 0xcc, 0x87, 0xa3, 0x5c, 0x94,
	0x89, 0x14, 0x91, 0xef, 0x8c, 0x9c, 0x49, 0x8f, 0xdb, 0x92, 0x5d, 0x81, 0x57, 0xc4, 0xdb, 0x4c,
	0xe8, 0x9d, 0x42, 0xbf, 0x31, 0x72, 0x26, 0xdd, 0xd9, 0x49, 0x50, 0x65, 0x04, 0x4b, 0x2b, 0xf0,
	0x5f, 0xcf, 0xf8, 0x0e, 0xbc, 0x9a, 0x67, 0x0c, 0x9a, 0xba, 0xcc, 0x91, 0x42, 0x3d, 0x4e, 0x98,
	0x5d, 0xfc, 0x4f, 0xec, 0xfd, 0x7d, 0xfe, 0x08, 0xfd, 0x17, 0x54, 0xa9, 0xc8, 0x64, 0x84, 0x4f,
	0xa8, 0x05, 0x1b, 0x80, 0xab, 0xb2, 0x68, 0x9f, 0x60, 0x20, 0x9b, 0xc2, 0x60, 0xad, 0x50, 0x68,
	0x5c, 0xe9, 0x38, 0xc5, 0x42, 0x8b, 0x34, 0xa7, 0x1c, 0x97, 0x1f, 0x57, 0xfc, 0xab, 0xa5, 0xc7,
	0xdf, 0x0e, 0x74, 0x1e, 0xe2, 0x04, 0x9f, 0x65, 0x84, 0x6c, 0x0a, 0xcd, 0x14, 0xb5, 0xa0, 0xa8,
	0xee, 0xec, 0xcc, 0x6e, 0x71, 0xd0, 0x8e, 0x93, 0x85, 0x0d, 0xa1, 0xb3, 0x89, 0x13, 0xcc, 0x44,
	0x5a, 0x8d, 0xe8, 0xf1, 0xba, 0x36, 0x3b, 0x15, 0xf1, 0x17, 0xfa, 0x2e, 0xb5, 0x24, 0xcc, 0xce,
	0xc1, 0x33, 0x37, 0x5e, 0x91, 0xd0, 0x24, 0xa1, 0x63, 0x88, 0xa5, 0x11, 0xe7, 0x40, 0x98, 0xe3,
	0xa6, 0xf0, 0x5b, 0x23, 0x77, 0xd2, 0x9d, 0x5d, 0xda, 0xde, 0x76, 0xb6, 0x60, 0xb1, 0x37, 0xdc,
	0x67, 0x5a, 0x95, 0xbc, 0xf6, 0x0f, 0x6f, 0xa1, 0x7f, 0x20, 0x99, 0x73, 0x7c, 0x60, 0x49, 0x3b,
	0xb8, 0xdc, 0x40, 0x76, 0x0a, 0xad, 0x4f, 0x91, 0xec, 0xec, 0xa0, 0x55, 0x31, 0x6f, 0xdc, 0x38,
	0x61, 0x9b, 0xbe, 0xfc, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xad, 0x23, 0xa3, 0x00, 0x02,
	0x00, 0x00,
}
